Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
import numpy as np

In [7]:
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [16]:
t = [
    a.reshape(6,2),
    a.reshape(2,6).T,
    a.reshape(2,6),
    a.reshape(6,2).T,
    a.reshape(3,4)
]

t

[array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 18],
        [13, 19],
        [14, 20],
        [15, 21],
        [16, 22],
        [17, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 14, 16, 18, 20, 22],
        [13, 15, 17, 19, 21, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [18]:
t = [
    a.reshape(6,-1),
    a.reshape(-1,6).T,
    a.reshape(-1,6),
    a.reshape(6,-1).T,
    a.reshape(3,-1)
]

t

[array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 18],
        [13, 19],
        [14, 20],
        [15, 21],
        [16, 22],
        [17, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 14, 16, 18, 20, 22],
        [13, 15, 17, 19, 21, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [22]:
type(a), np.shape(a)
# да, так как это векторизованный объект, а вектор яно одномерный массив

(numpy.ndarray, (12,))

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [82]:
np.random.seed(0)
matrix = np.random.randn(12)
matrix.reshape(3, 4)
np.mean(matrix), np.std(matrix), matrix.size

(0.74821239878435, 0.9227225327547848, 12)

In [83]:
matrix_mono = matrix.reshape(1, 12)
matrix_mono.size

12

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2

In [85]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [88]:
b = a.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [91]:
a == b
# нет разницы

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10

In [148]:
a = np.arange(1, 5, 1)
a[...] = 0
a = a.reshape(2, 2)

a

array([[0, 0],
       [0, 0]])

In [149]:
b = np.arange(1, 7, 1)
b[...] = 1
b = b.reshape(3, 2)

b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [150]:
v = np.vstack((a, b))
v

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1]])

In [151]:
v.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [164]:
a = np.arange(0, 12, 1)
A = a.reshape(4, 3)
At = A.T
B = A @ At
B.shape, B

((4, 4),
 array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]))

In [165]:
# результат умножения матриц 4х4 так как результат состоит из мак. количества строк и макс. количества столбцов

In [168]:
np.linalg.det(B)
# определитель матрицы равен нулю, матрица сингулярная (вырожденная, что бы это не значило)
# np.linalg.inv(B)

0.0

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42

In [175]:
np.random.seed(42)
np.random.randint(1, 10)

7

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [179]:
c = np.random.randint(0, 16, 16)
c

array([10, 10, 14,  9, 15, 11, 11, 15, 14, 13, 13, 14, 13,  2, 11,  6])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [181]:
C = c.reshape(4, 4)
C

array([[10, 10, 14,  9],
       [15, 11, 11, 15],
       [14, 13, 13, 14],
       [13,  2, 11,  6]])

In [182]:
D = B + (C * 10) # да, умножение выполнится первым, но я поставил скобки
D, B, C * 10

(array([[105, 114, 163, 122],
        [164, 160, 196, 272],
        [163, 216, 279, 352],
        [162, 142, 322, 362]]),
 array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 array([[100, 100, 140,  90],
        [150, 110, 110, 150],
        [140, 130, 130, 140],
        [130,  20, 110,  60]]))

In [183]:
D_inv = np.linalg.inv(D)
np.linalg.det(D), np.linalg.matrix_rank(D), D_inv

(119867200.00000036,
 4,
 array([[ 0.00532189,  0.01963339, -0.01794786,  0.00090634],
        [ 0.00359464, -0.00609224,  0.01394944, -0.01019795],
        [ 0.00906737, -0.01076758, -0.00033103,  0.00535659],
        [-0.01185712,  0.00318135,  0.00285449,  0.00159243]]))

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [185]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1

In [186]:
D_inv

array([[1., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 1.]])

In [187]:
D_inv, B, C

(array([[1., 1., 0., 1.],
        [1., 0., 1., 0.],
        [1., 0., 0., 1.],
        [0., 1., 1., 1.]]),
 array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 array([[10, 10, 14,  9],
        [15, 11, 11, 15],
        [14, 13, 13, 14],
        [13,  2, 11,  6]]))

In [189]:
E = np.where(D_inv > 0, B, C)
E

array([[  5,  14,  14,  32],
       [ 14,  11,  86,  15],
       [ 23,  13,  13, 212],
       [ 13, 122, 212, 302]])